# -*- coding: utf-8 -*-
"""CV LAB-05

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pg4DCM9q0H1hfGK35y0OjUiFds8mL0e5
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

def separate_lsb(image):
    lsb_plane = (image >> 0) & 1
    lsb_plane = lsb_plane * 255
    return lsb_plane.astype(np.uint8)

img = cv2.imread("/content/rose.webp", cv2.IMREAD_GRAYSCALE)

lsb_image = separate_lsb(img)

plt.figure(figsize=(10, 5))

plt.subplot(1, 2, 1)
plt.imshow(img, cmap='gray')
plt.title('Original Image')
plt.axis('off')

plt.subplot(1, 2, 2)
plt.imshow(lsb_image, cmap='gray')
plt.title('LSB Plane (Bit Plane 0)')
plt.axis('off')

plt.tight_layout()
plt.show()